# Generated by Django 2.1.4 on 2019-01-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dox',
            name='upload',
            field=models.FileField(null=True, upload_to='static/word/documents/%Y/%m/%d/'),
        ),
    ]
